### PR TITLE
Translations update from Weblate

### PR DESCRIPTION
**Pull request by jvir**
Translations update from [Weblate](http://trans.etranslator.eu/projects/fvtt-swade-spices-flavours/en-json/) for FVTT-SWADE-Spices-Flavours/en.json.

Current translation status:

Weblate translation status

### CODE REVIEW

**Comment by parvusdomus** [comment]
Just finished it. JuanV will send it asap

**Comment by SalieriC** [comment]
@all-contributors please add @jvir and @parvusdomus for translation.

**Comment by SalieriC** [comment]
@all-contributors please add @jvir for translation

**Comment by SalieriC** [comment]
@all-contributors please add @jvir and @parvusdomus for translation.

**Comment by SalieriC** [comment]
@all-contributors please add @parvusdomus for translation.

**Pull request merged**
